# app/config/security.yml
security:
    encoders:
          AppBundle\Entity\User: plaintext
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]
    providers:
        users:
            entity: { class: AppBundle\Entity\User, property: username }
    firewalls:
        default:
            anonymous: ~
            http_basic: ~
            form_login:
                login_path: /login
                check_path: /login_check
            logout:
                invalidate_session: true
                path:   /logout
                target: /secured/show-categories

    access_control:
        # require ROLE_ADMIN for /admin*
        - { path: ^/secured/*, roles: ROLE_USER }
