services:
  thread.form.type:
    class: AppBundle\Form\Type\ThreadFormType
    tags:
      - { name: form.type, alias: thread }

  post.form.type:
    class: AppBundle\Form\Type\PostFormType
    tags:
      - { name: form.type, alias: post }